# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94c52e3748f645604e9d6e395d8eedda40657c75b5ebb6a796420e64f3a160bebaf8ad475ef03d337bd88aa07b41126cc70effefba3416c5314466df42b78c73

test:
  secret_key_base: 21a1e3827afbef77f06b769da67e81823997c12d440e1c042c6510dd8541b366a21f6874db0e52dc2ac717cc327044b8271cf4215f763194b2e9cc8ef39563c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
